name: schedule-test

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Print event and time
        run: |
          echo "GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
          date -u